version: '3.9'
networks:
  backend:
    driver: bridge
services:
  node-server:
    container_name: node-server
    build: .
    image: enzo/node-server
    networks:
      - backend
    ports:
      - '3000:3000'
      # variables de entorno de node-server
    environment:
      - DB_HOST=mysql-database
      - DB_USERNAME=user
      - DB_PASSWORD=pass
      - DB_DATABASE=auth
      - DB_DIALECT=mysql
      - AUTH_SECRET=jwt+sequelize
      - AUTH_EXPIRES=1d
      - AUTH_SALT=10
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      mysql-database:
        condition: service_healthy

  mysql-database:
    container_name: mysql-database
    image: mysql
    # para la distinción de mayusculas y mínusculas en Linux
    command: --lower_case_table_names=1
    # variables de entorno de mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=auth
    networks:
      - backend
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 15s
      retries: 1
    cap_add:
      - SYS_NICE